-- MySQL Script generated by MySQL Workbench
-- Fr 29 Jan 2016 16:15:35 CET
-- Model: InstalistServer    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema instalist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema instalist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instalist` DEFAULT CHARACTER SET utf8 ;
USE `instalist` ;

-- -----------------------------------------------------
-- Table `instalist`.`devicegroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`devicegroups` ;

CREATE TABLE IF NOT EXISTS `instalist`.`devicegroups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `readableid` CHAR(6) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`devices` ;

CREATE TABLE IF NOT EXISTS `instalist`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `autorizedtogroup` TINYINT(1) NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `secret` BINARY(60) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devices_devicegroups_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_devices_devicegroups`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`categories` ;

CREATE TABLE IF NOT EXISTS `instalist`.`categories` (
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_categories_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_categories_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`lists` ;

CREATE TABLE IF NOT EXISTS `instalist`.`lists` (
  `uuid` CHAR(36) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `category_uuid` CHAR(36) NULL,
  `name` VARCHAR(256) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_lists_devicegroups1_idx` (`devicegroup_id` ASC),
  INDEX `fk_lists_categories1_idx` (`category_uuid` ASC),
  CONSTRAINT `fk_lists_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lists_categories1`
    FOREIGN KEY (`category_uuid`)
    REFERENCES `instalist`.`categories` (`uuid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`units` ;

CREATE TABLE IF NOT EXISTS `instalist`.`units` (
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_units_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_units_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`products` ;

CREATE TABLE IF NOT EXISTS `instalist`.`products` (
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `default_amount` REAL NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `unit_uuid` CHAR(36) NULL,
  `step_amount` REAL NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_products_devicegroups1_idx` (`devicegroup_id` ASC),
  INDEX `fk_products_units1_idx` (`unit_uuid` ASC),
  CONSTRAINT `fk_products_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_units1`
    FOREIGN KEY (`unit_uuid`)
    REFERENCES `instalist`.`units` (`uuid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`list_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`list_entries` ;

CREATE TABLE IF NOT EXISTS `instalist`.`list_entries` (
  `uuid` CHAR(36) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `list_uuid` INT NOT NULL,
  `product_uuid` CHAR(36) NOT NULL,
  `amount` INT NOT NULL,
  `striked` TINYINT(1) NOT NULL,
  `priority` INT NOT NULL DEFAULT 0,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_list_entries_devicegroups1_idx` (`devicegroup_id` ASC),
  INDEX `fk_list_entries_lists1_idx` (`list_uuid` ASC),
  INDEX `fk_list_entries_products1_idx` (`product_uuid` ASC),
  CONSTRAINT `fk_list_entries_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_entries_lists1`
    FOREIGN KEY (`list_uuid`)
    REFERENCES `instalist`.`lists` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_entries_products1`
    FOREIGN KEY (`product_uuid`)
    REFERENCES `instalist`.`products` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`recipes` ;

CREATE TABLE IF NOT EXISTS `instalist`.`recipes` (
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `devicegroups_id` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroups_id`),
  INDEX `fk_recipes_devicegroups1_idx` (`devicegroups_id` ASC),
  CONSTRAINT `fk_recipes_devicegroups1`
    FOREIGN KEY (`devicegroups_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `instalist`.`ingredients` (
  `uuid` CHAR(36) NOT NULL,
  `amount` REAL NOT NULL,
  `product_uuid` CHAR(36) NOT NULL,
  `recipe_uuid` CHAR(36) NOT NULL,
  `devicegroups_id` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroups_id`),
  INDEX `fk_ingredients_products1_idx` (`product_uuid` ASC),
  INDEX `fk_ingredients_recipes1_idx` (`recipe_uuid` ASC),
  INDEX `fk_ingredients_devicegroups1_idx` (`devicegroups_id` ASC),
  CONSTRAINT `fk_ingredients_products1`
    FOREIGN KEY (`product_uuid`)
    REFERENCES `instalist`.`products` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_recipes1`
    FOREIGN KEY (`recipe_uuid`)
    REFERENCES `instalist`.`recipes` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_devicegroups1`
    FOREIGN KEY (`devicegroups_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`tags` ;

CREATE TABLE IF NOT EXISTS `instalist`.`tags` (
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_tags_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_tags_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`tagged_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`tagged_products` ;

CREATE TABLE IF NOT EXISTS `instalist`.`tagged_products` (
  `uuid` VARCHAR(256) NOT NULL,
  `product_uuid` CHAR(36) NOT NULL,
  `tags_uuid` CHAR(36) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_tagged_products_products1_idx` (`product_uuid` ASC),
  INDEX `fk_tagged_products_tags1_idx` (`tags_uuid` ASC),
  PRIMARY KEY (`uuid`, `devicegroup_id`),
  INDEX `fk_tagged_products_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_tagged_products_products1`
    FOREIGN KEY (`product_uuid`)
    REFERENCES `instalist`.`products` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagged_products_tags1`
    FOREIGN KEY (`tags_uuid`)
    REFERENCES `instalist`.`tags` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagged_products_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
