-- MySQL Script generated by MySQL Workbench
-- So 28 Feb 2016 11:23:22 CET
-- Model: InstalistServer    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema instalist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema instalist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instalist` DEFAULT CHARACTER SET utf8 ;
USE `instalist` ;

-- -----------------------------------------------------
-- Table `instalist`.`devicegroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`devicegroups` ;

CREATE TABLE IF NOT EXISTS `instalist`.`devicegroups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `readableid` CHAR(6) NULL,
  `created` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`devices` ;

CREATE TABLE IF NOT EXISTS `instalist`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `authorized` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `secret` VARCHAR(255) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devices_devicegroups_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_devices_devicegroups`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`categories` ;

CREATE TABLE IF NOT EXISTS `instalist`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `fk_categories_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_categories_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`lists` ;

CREATE TABLE IF NOT EXISTS `instalist`.`lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `category_id` INT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lists_devicegroups1_idx` (`devicegroup_id` ASC),
  INDEX `fk_lists_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_lists_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lists_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `instalist`.`categories` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`units` ;

CREATE TABLE IF NOT EXISTS `instalist`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_units_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_units_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`products` ;

CREATE TABLE IF NOT EXISTS `instalist`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `defaultamount` FLOAT NOT NULL,
  `stepamount` FLOAT NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  `unit_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_devicegroups1_idx` (`devicegroup_id` ASC),
  INDEX `fk_products_units1_idx` (`unit_id` ASC),
  CONSTRAINT `fk_products_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_units1`
    FOREIGN KEY (`unit_id`)
    REFERENCES `instalist`.`units` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`list_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`list_entries` ;

CREATE TABLE IF NOT EXISTS `instalist`.`list_entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `amount` FLOAT NOT NULL,
  `list_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `struck` TINYINT(1) NOT NULL,
  `priority` INT NOT NULL DEFAULT 0,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  INDEX `fk_list_entries_devicegroups1_idx` (`devicegroup_id` ASC),
  INDEX `fk_list_entries_lists1_idx` (`list_id` ASC),
  INDEX `fk_list_entries_products1_idx` (`product_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_list_entries_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_entries_lists1`
    FOREIGN KEY (`list_id`)
    REFERENCES `instalist`.`lists` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_entries_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `instalist`.`products` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`recipes` ;

CREATE TABLE IF NOT EXISTS `instalist`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_recipes_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `instalist`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `amount` FLOAT NOT NULL,
  `product_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredients_products1_idx` (`product_id` ASC),
  INDEX `fk_ingredients_recipes1_idx` (`recipe_id` ASC),
  INDEX `fk_ingredients_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_ingredients_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `instalist`.`products` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `instalist`.`recipes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`tags` ;

CREATE TABLE IF NOT EXISTS `instalist`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `fk_tags_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_tags_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`tagged_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`tagged_products` ;

CREATE TABLE IF NOT EXISTS `instalist`.`tagged_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `product_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devicegroup_id` INT NOT NULL,
  INDEX `fk_tagged_products_products1_idx` (`product_id` ASC),
  INDEX `fk_tagged_products_tags1_idx` (`tag_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_tagged_products_devicegroups1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_tagged_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `instalist`.`products` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagged_products_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `instalist`.`tags` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagged_products_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalist`.`deletion_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instalist`.`deletion_log` ;

CREATE TABLE IF NOT EXISTS `instalist`.`deletion_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `devicegroup_id` INT NOT NULL,
  `type` INT NOT NULL,
  `updated` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `fk_deletion_log_devicegroups1_idx` (`devicegroup_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_deletion_log_devicegroups1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `instalist`.`devicegroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
