instalist_topic:
    channel: instalist/channel/{section}
    handler:
        callback: 'instalist.topic' #related to the getName() of your topic
    requirements:
        section:
            pattern: "[a-z]+"

instalist_rpc:
    channel: instalist/{method}
    handler:
        callback: 'instalist.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+"
