services:
    instalist.topic_updatenotifier_service:
        class: InstalistBundle\Topic\InstalistTopic
        tags:
            - { name: gos_web_socket.topic }


    instalist.rpc_service:
        class: InstalistBundle\Rpc\InstalistRpc
        tags:
            - { name: gos_web_socket.rpc } 
